[package]
name = "dwarf-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
rust_decimal = "1.30.0"
serde = { version = "1.0.177", features = ["derive"] }
Lotus = "0.2.1"